# Generated by Django 5.1.2 on 2024-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_unica', models.CharField(max_length=255, unique=True, verbose_name='Identificação única')),
                ('rfid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RFID')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
