# Generated by Django 5.1.2 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bois/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
